from .toolkit.colors import Colors as _C
import time


def Test(psu):
    psu.stateDigital()
    print()
    psu.setAddr(0x01)
    print()
    psu.deviceInfo()
    print()
    psu.getPhysics()
    print()
    psu.getError()
    print()
    psu.clearError()
    print()
    #input(_C.BOLD + _C.MAGENTA + "Ready for turn on [Press any key]" + _C.ENDC)
    psu.turnOn()
    print()
    psu.setCurrentLimit(limit=1)
    print()
    # Voltage ramping test
    psu.setVoltage(voltage=5)
    time.sleep(1)
    print()
    psu.getPhysics()
    print()
    psu.setVoltage(voltage=10)
    time.sleep(1)
    print()
    psu.getPhysics()
    print()
    psu.setVoltage(voltage=15)
    time.sleep(1)
    print()
    psu.getPhysics()
    print()
    psu.setVoltage(voltage=0)
    print()
    psu.getCurrentLimit()
    print()
    #input(_C.BOLD + _C.MAGENTA + "Ready for turn off [Press any key]" + _C.ENDC)
    psu.turnOff()
